"""empty message

Revision ID: 5c1eb4e99b4b
Revises: 782b731c546a
Create Date: 2026-01-18 13:10:47.370288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1eb4e99b4b'
down_revision = '782b731c546a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('motto', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_column('motto')
        batch_op.drop_column('logo')

    # ### end Alembic commands ###
