"""empty message

Revision ID: 782b731c546a
Revises: 3d01a4d952f0
Create Date: 2026-01-18 11:55:52.356815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782b731c546a'
down_revision = '3d01a4d952f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
