"""is_super_admin column added

Revision ID: c15c6fd83015
Revises: 6c04eb9b208b
Create Date: 2026-04-16 04:01:32.838552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15c6fd83015'
down_revision = '6c04eb9b208b'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        'teachers',
        sa.Column(
            'is_super_admin',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()  # 👈 THIS is the fix
        )
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('is_super_admin')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'])

    with op.batch_alter_table('exam_papers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'subjects', ['subject_id'], ['id'])

    # ### end Alembic commands ###
