"""added grading system tables

Revision ID: fd65e3f41dab
Revises: dcf624f5c9d8
Create Date: 2026-01-11 11:09:52.646214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd65e3f41dab'
down_revision = 'dcf624f5c9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grading_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('grading_schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['grading_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_grading_schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['branch_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheme_id'], ['grading_schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grading_boundaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('performance_level', sa.String(length=20), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('descriptor', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['grading_schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grading_boundaries')
    op.drop_table('grade_grading_schemes')
    op.drop_table('grading_schemes')
    op.drop_table('grading_systems')
    # ### end Alembic commands ###
